/* Generated By:JavaCC: Do not edit this line. MainParserConstants.java */
package st.chimera.mips.assembler;

public interface MainParserConstants {

  int EOF = 0;
  int SPACE = 1;
  int EOL = 2;
  int REGISTER = 3;
  int RAW_REG = 4;
  int ZERO_REG = 5;
  int AT_REG = 6;
  int VAL_REG = 7;
  int ARG_REG = 8;
  int TMP_REG = 9;
  int SAV_REG = 10;
  int KER_REG = 11;
  int GP_REG = 12;
  int SP_REG = 13;
  int FP_REG = 14;
  int RA_REG = 15;
  int ROPCODE_RD_RT_SHAMT = 16;
  int ROPCODE_RD_RT_RS = 17;
  int ROPCODE_NONE = 18;
  int ROPCODE_RD = 19;
  int ROPCODE_RS = 20;
  int ROPCODE_RS_RT = 21;
  int ROPCODE_RD_RS_RT = 22;
  int IOPCODE_RS_RT_LABEL = 23;
  int IOPCODE_RS_LABEL = 24;
  int IOPCODE_RT_RS_IMM = 25;
  int IOPCODE_RT_IMM = 26;
  int IOPCODE_RT_ADDR = 27;
  int JOPCODE = 28;
  int IDENTIFIER_COLON = 29;
  int DECIMAL_COLON = 30;
  int IDENTIFIER = 31;
  int DECIMAL = 32;
  int HEXADECIMAL = 33;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<SPACE>",
    "<EOL>",
    "<REGISTER>",
    "<RAW_REG>",
    "\"zero\"",
    "\"at\"",
    "<VAL_REG>",
    "<ARG_REG>",
    "<TMP_REG>",
    "<SAV_REG>",
    "<KER_REG>",
    "\"gp\"",
    "\"sp\"",
    "\"fp\"",
    "\"ra\"",
    "<ROPCODE_RD_RT_SHAMT>",
    "<ROPCODE_RD_RT_RS>",
    "\"syscall\"",
    "<ROPCODE_RD>",
    "<ROPCODE_RS>",
    "<ROPCODE_RS_RT>",
    "<ROPCODE_RD_RS_RT>",
    "<IOPCODE_RS_RT_LABEL>",
    "<IOPCODE_RS_LABEL>",
    "<IOPCODE_RT_RS_IMM>",
    "\"lui\"",
    "<IOPCODE_RT_ADDR>",
    "<JOPCODE>",
    "<IDENTIFIER_COLON>",
    "<DECIMAL_COLON>",
    "<IDENTIFIER>",
    "<DECIMAL>",
    "<HEXADECIMAL>",
    "\",\"",
    "\"(\"",
    "\")\"",
  };

}
